package chunking

// CodeChunk represents an AST-extracted code chunk
type CodeChunk struct {
	Content   string   `json:"content"`
	Type      string   `json:"type"`      // function, class, method, type
	Name      string   `json:"name"`
	StartLine int      `json:"start_line"`
	EndLine   int      `json:"end_line"`
	FilePath  string   `json:"file_path"`
	Signature string   `json:"signature,omitempty"` // Function signature
	Imports   []string `json:"imports,omitempty"`
	Language  string   `json:"language"`
}

// DocChunk represents a contextually enriched document chunk
type DocChunk struct {
	OriginalContent string `json:"original_content"`
	Context         string `json:"context"`         // Generated by Haiku
	EnrichedContent string `json:"enriched_content"` // Context + Original
	FilePath        string `json:"file_path"`
	Section         string `json:"section"`
	StartLine       int    `json:"start_line"`
	EndLine         int    `json:"end_line"`
}

// MarkdownSection represents a section extracted from markdown
type MarkdownSection struct {
	Title     string
	Content   string
	Level     int
	StartLine int
	EndLine   int
}
