package guard

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/anthropics/aef/edi/internal/config"
	"gopkg.in/yaml.v3"
)

// CompactionSnapshotPolicy writes session state to /memories/ before compaction.
type CompactionSnapshotPolicy struct {
	cfg *config.GuardConfig
}

// NewCompactionSnapshotPolicy returns a policy that snapshots session state.
func NewCompactionSnapshotPolicy(cfg *config.GuardConfig) *CompactionSnapshotPolicy {
	return &CompactionSnapshotPolicy{cfg: cfg}
}

func (c *CompactionSnapshotPolicy) Name() string { return "compaction-snapshot" }

func (c *CompactionSnapshotPolicy) OnPreCompact(_ context.Context, hctx *HookContext) {
	var lines []string
	lines = append(lines, "# Session State (auto-generated by edi-guard before compaction)")

	// Tasks
	if tasks := readActiveTasks(hctx.CWD); len(tasks) > 0 {
		for i, t := range tasks {
			if i >= 2 {
				remaining := len(tasks) - 2
				lines[len(lines)-1] += fmt.Sprintf(" (+%d more)", remaining)
				break
			}
			lines = append(lines, fmt.Sprintf("- Task: %s — %s", t.id, t.subject))
		}
	}

	// Git branch
	if branch := gitBranch(); branch != "" {
		lines = append(lines, fmt.Sprintf("- Branch: %s", branch))
	}

	// Build tags
	if len(c.cfg.BuildTags) > 0 {
		lines = append(lines, fmt.Sprintf("- Build tags required: %s", strings.Join(c.cfg.BuildTags, ", ")))
	}

	// Last test result
	state := readState(hctx.SessionID)
	if state.ConsecutiveFailures > 0 {
		lines = append(lines, fmt.Sprintf("- Last test result: %d consecutive failures (last: %q → %q)",
			state.ConsecutiveFailures, state.LastFailureCommand, state.LastFailureError))
	} else {
		lines = append(lines, "- Last test result: no recent failures")
	}

	// Agent mode (from HookContext, not GuardConfig)
	if hctx.Agent != "" {
		lines = append(lines, fmt.Sprintf("- Agent mode: %s", hctx.Agent))
	}

	// Compaction trigger
	if hctx.Input.Trigger != "" {
		lines = append(lines, fmt.Sprintf("- Compaction trigger: %s", hctx.Input.Trigger))
	}

	// Write file
	dir := filepath.Join(hctx.CWD, "memories")
	if err := os.MkdirAll(dir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "edi-guard: failed to create memories dir: %v\n", err)
		return
	}
	content := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(filepath.Join(dir, "compaction-state.md"), []byte(content), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "edi-guard: failed to write compaction-state.md: %v\n", err)
	}
}

// --- Unexported helpers (single-use within this policy) ---

type taskInfo struct {
	id      string
	subject string
}

func readActiveTasks(cwd string) []taskInfo {
	data, err := os.ReadFile(filepath.Join(cwd, ".edi", "tasks", "active.yaml"))
	if err != nil {
		return nil
	}
	var manifest struct {
		Tasks []struct {
			ID      string `yaml:"id"`
			Subject string `yaml:"subject"`
			Status  string `yaml:"status"`
		} `yaml:"tasks"`
	}
	if err := yaml.Unmarshal(data, &manifest); err != nil {
		return nil
	}
	var result []taskInfo
	for _, t := range manifest.Tasks {
		if t.Status == "in_progress" {
			result = append(result, taskInfo{id: t.ID, subject: t.Subject})
		}
	}
	return result
}

func gitBranch() string {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	out, err := exec.CommandContext(ctx, "git", "branch", "--show-current").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
